---
title: "Regression_Class-Assign-3"
author: "Stephanie N. Pham"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(dplyr)
library(gridExtra)
library(Rfit)
library(MASS)

#######################################################

# Bring in the "tvmarketing.csv" data
data <- read.csv(file = "data/3_tvmarketing.csv")

```


Upload Sales vs. TV Budget scatterplot
```{r 1}
plot(data$Sales,data$TV, 
     main="Scatterplot of Sales vs. TV Budget", 
     xlab="Sales", 
     ylab="TV Budget", 
     col="navy", 
     bg="navy",
     cex=1.25, 
     pch=19)
```



```{r 2, echo=FALSE}

slr = lm(data$TV~data$Sales) 
stud = rstudent(slr)
slr_fit = fitted(slr)


plot(slr_fit, stud,
     main="Studentized Residuals vs. Predicted", 
     xlab="Sales", 
     ylab="Studentized Residuals",
     ylim=(c(-4, 4))
     );
abline(h = 0,col = 'violet')
abline(h = 2.5,col = 'blueviolet')
abline(h = -2.5,col = 'blueviolet')
```
```{r 3}
#Q-Q Plot
qqnorm(stud,pch = 16);abline(0,1, col="red")

```
Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

```{r 5}

bc = boxcox(slr)

```

```{r 6}
# Scatterplot
plot(data$Sales,data$TV, 
     main="Scatterplot of Sales vs. TV Budget", 
     xlab="Sales", 
     ylab="TV Budget", 
     col="navy", 
     bg="navy",
     cex=1.25, 
     pch=19)

# Studentized residuals
slr_bc = lm(powerTransform(y, lambda) ~ x)
stud_bc = rstudent(slr_bc)
slr_fit_bc = fitted(slr_bc)

plot(slr_fit_bc, stud_bc,
     main="Studentized Residuals vs. Predicted", 
     xlab="Sales", 
     ylab="Studentized Residuals",
     ylim=(c(-4, 4))
     );
abline(h = 0,col = 'violet')
abline(h = 2.5,col = 'blueviolet')
abline(h = -2.5,col = 'blueviolet')

# Q-Q Plot
qqnorm(stud_bc,pch = 16);abline(0,1, col="navy")


```